job_summary_patterns = [
    'about the job',
    'description',
    'job description',
    'what we expect',
    'about the role',
    'who are we looking for',
    'role overview']

job_responsibilities_patterns = [
    "Product Strategy Duties",
    "Core Responsibilities",
    "What will you do",
    "What You'll Do",
    "What you'll be doing",
    "You will",
    "Responsibilities",
    "Your Responsibilities",
    "Role Responsibilities",
    "Roles and Responsibilities",
    "Main responsibilities will be",
    "Your role",
    "The role",
    "About the Role",
    "Your mission",
    "Job duties",
    "What You Get To Do Every Day",
    "You will have the opportunity to",
    # f"Our {title} can possibly:",
    "In one year you'll know you were successful if"
]

job_minimum_requirement_patterns = [
    "We have a few concrete requirements",
    "Only those who can fulfill the following requirements",
    "Current Tech Stack",
    "Qualifications",
    "Desired Skills",
    'What We Need From You',
    'Requirements',
    'You have',
    'Key requirements',
    'What excites us about you',
    'Skills Required',
    "What We're Looking For ",
    "What We're Looking For in you",
    'Who You Are',
    'What we are looking for',
    'About you',
    'What we look for',
    'What we expect from you',
    'You',
    'This might describe you',
    'What you need to have',
    'Who You Are',
    'A background like this helps',
    'If you',
    'Education and Experience Required',
    'Knowledge and Skills']

job_preferred_requirement_patterns = [
    "Bonus",
    "Bonus if you have",
    "Prefer",
    "What will be great to have",
    "Nice to have",
    "Bonus Points:",
    "Big Plus"
]
job_benefit_patterns = [
    "Why take this job",
    "Why work with us",
    "What we offer",
    "Why are we awesome you ask",
    "Why might you be excited about this role",
    "Why might you not be excited about this role",
    "You get",
    "What’s in for you",
    "Why join",
    "You will get",
    "Additionally, you will get",
    "Perks ",
    "Some of the perks while at",
    "We offer",
    "Benefits & Perks",
    "Benefits",
]